--------------------------------------------------------
--  File created - Sunday-November-26-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BB_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."BB_EMPLOYEE" 
   (	"BBE_ID" VARCHAR2(15 BYTE), 
	"BB_ID" VARCHAR2(15 BYTE), 
	"USER_ID" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BLOOD_BANK
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."BLOOD_BANK" 
   (	"BB_ID" VARCHAR2(15 BYTE), 
	"BB_NAME" VARCHAR2(50 BYTE), 
	"STATE_ID" VARCHAR2(15 BYTE), 
	"CITY_ID" VARCHAR2(15 BYTE), 
	"LOC_ID" VARCHAR2(15 BYTE), 
	"CONTACT" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"CREATED_BY" VARCHAR2(15 BYTE), 
	"CREATED_DATE" DATE, 
	"DELETED" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BLOOD_REQUEST
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."BLOOD_REQUEST" 
   (	"BR_ID" VARCHAR2(15 BYTE), 
	"REG_ID" VARCHAR2(15 BYTE), 
	"BB_ID" VARCHAR2(15 BYTE), 
	"CONTACT" VARCHAR2(10 BYTE), 
	"BLD_GROUP" VARCHAR2(20 BYTE), 
	"QTY" NUMBER, 
	"REQ_STATUS" VARCHAR2(20 BYTE), 
	"REQ_DATE" DATE, 
	"ASSIGNTO_EMP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BLOODDONATION_HISTORY
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."BLOODDONATION_HISTORY" 
   (	"BDH_ID" VARCHAR2(15 BYTE), 
	"REG_ID" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"BB_ID" VARCHAR2(15 BYTE), 
	"BGROUP" VARCHAR2(20 BYTE), 
	"QTY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CITY_INFO
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."CITY_INFO" 
   (	"CITY_ID" VARCHAR2(15 BYTE), 
	"CITY_NAME" VARCHAR2(50 BYTE), 
	"STATE_ID" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATE_INFO
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."STATE_INFO" 
   (	"STATE_ID" VARCHAR2(15 BYTE), 
	"STATE_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BLOODBANK"."STATE_INFO"."STATE_ID" IS 'State Id';
   COMMENT ON COLUMN "BLOODBANK"."STATE_INFO"."STATE_NAME" IS 'Name of State';
--------------------------------------------------------
--  DDL for Table REGISTRATION
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."REGISTRATION" 
   (	"REG_ID" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"CONTACT" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"BIRTH_DATE" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(5 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"PINCODE" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOGIN_DETAIL
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."LOGIN_DETAIL" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"SEC_QUESTION" VARCHAR2(100 BYTE), 
	"ANSWER" VARCHAR2(50 BYTE), 
	"PROFILE_ID" VARCHAR2(15 BYTE), 
	"USER_ROLE" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATION_INFO
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."LOCATION_INFO" 
   (	"LOC_ID" VARCHAR2(15 BYTE), 
	"LOC_NAME" VARCHAR2(50 BYTE), 
	"CITY_ID" VARCHAR2(50 BYTE), 
	"PIN_CODE" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INQUIRY
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."INQUIRY" 
   (	"INQ_ID" VARCHAR2(15 BYTE), 
	"INQUIRED_BY" VARCHAR2(50 BYTE), 
	"INQ_SUBJECT" VARCHAR2(100 BYTE), 
	"INQUIRY" VARCHAR2(1000 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"INQ_DATE" DATE, 
	"INQ_STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FEEDBACK
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."FEEDBACK" 
   (	"F_ID" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"FEEDBACK" VARCHAR2(2000 BYTE), 
	"INQ_ID" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPREQ_ASSIGNMENT
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."EMPREQ_ASSIGNMENT" 
   (	"EA_ID" VARCHAR2(15 BYTE), 
	"U_ID" VARCHAR2(15 BYTE), 
	"E_ID" VARCHAR2(15 BYTE), 
	"MSG" VARCHAR2(1000 BYTE), 
	"REQ_ID" VARCHAR2(15 BYTE), 
	"REQ_STATUS" VARCHAR2(20 BYTE), 
	"APP_DATE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPDON_ASSIGNMENT
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."EMPDON_ASSIGNMENT" 
   (	"EDA_ID" VARCHAR2(15 BYTE), 
	"USER_ID" VARCHAR2(15 BYTE), 
	"EMP_ID" VARCHAR2(15 BYTE), 
	"DONREQ_ID" VARCHAR2(15 BYTE), 
	"MSG" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."EMP" 
   (	"EMPNO" NUMBER(4,0), 
	"ENAME" VARCHAR2(10 BYTE), 
	"JOB" VARCHAR2(9 BYTE), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DONATION
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."DONATION" 
   (	"D_ID" VARCHAR2(15 BYTE), 
	"REG_ID" VARCHAR2(15 BYTE), 
	"BB_ID" VARCHAR2(15 BYTE), 
	"BGROUP" VARCHAR2(20 BYTE), 
	"QTY" NUMBER, 
	"D_DATE" DATE, 
	"PROCESSED_BY" VARCHAR2(15 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"AVAILABLITY" VARCHAR2(20 BYTE), 
	"DONATED_QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DNAME" VARCHAR2(14 BYTE), 
	"LOC" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEMO_USERS
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."DEMO_USERS" 
   (	"USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(4000 BYTE), 
	"CREATED_ON" DATE, 
	"QUOTA" NUMBER, 
	"PRODUCTS" CHAR(1 BYTE), 
	"EXPIRES_ON" DATE, 
	"ADMIN_USER" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEMO_STATES
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."DEMO_STATES" 
   (	"ST" VARCHAR2(30 BYTE), 
	"STATE_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEMO_PRODUCT_INFO
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."DEMO_PRODUCT_INFO" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(50 BYTE), 
	"PRODUCT_DESCRIPTION" VARCHAR2(2000 BYTE), 
	"CATEGORY" VARCHAR2(30 BYTE), 
	"PRODUCT_AVAIL" VARCHAR2(1 BYTE), 
	"LIST_PRICE" NUMBER(8,2), 
	"PRODUCT_IMAGE" BLOB, 
	"MIMETYPE" VARCHAR2(255 BYTE), 
	"FILENAME" VARCHAR2(400 BYTE), 
	"IMAGE_LAST_UPDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PRODUCT_IMAGE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DEMO_ORDERS
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."DEMO_ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"CUSTOMER_ID" NUMBER, 
	"ORDER_TOTAL" NUMBER(8,2), 
	"ORDER_TIMESTAMP" DATE, 
	"USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEMO_ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."DEMO_ORDER_ITEMS" 
   (	"ORDER_ITEM_ID" NUMBER(3,0), 
	"ORDER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"UNIT_PRICE" NUMBER(8,2), 
	"QUANTITY" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEMO_CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "BLOODBANK"."DEMO_CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER, 
	"CUST_FIRST_NAME" VARCHAR2(20 BYTE), 
	"CUST_LAST_NAME" VARCHAR2(20 BYTE), 
	"CUST_STREET_ADDRESS1" VARCHAR2(60 BYTE), 
	"CUST_STREET_ADDRESS2" VARCHAR2(60 BYTE), 
	"CUST_CITY" VARCHAR2(30 BYTE), 
	"CUST_STATE" VARCHAR2(2 BYTE), 
	"CUST_POSTAL_CODE" VARCHAR2(10 BYTE), 
	"PHONE_NUMBER1" VARCHAR2(25 BYTE), 
	"PHONE_NUMBER2" VARCHAR2(25 BYTE), 
	"CREDIT_LIMIT" NUMBER(9,2), 
	"CUST_EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BB_EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."BB_EMPLOYEE_PK" ON "BLOODBANK"."BB_EMPLOYEE" ("BBE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BLOOD_BANK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."BLOOD_BANK_PK" ON "BLOODBANK"."BLOOD_BANK" ("BB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BLOOD_REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."BLOOD_REQUEST_PK" ON "BLOODBANK"."BLOOD_REQUEST" ("BR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CITY_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."CITY_INFO_PK" ON "BLOODBANK"."CITY_INFO" ("CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATE_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."STATE_INFO_PK" ON "BLOODBANK"."STATE_INFO" ("STATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGISTRATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."REGISTRATION_PK" ON "BLOODBANK"."REGISTRATION" ("REG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOGIN_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."LOGIN_DETAIL_PK" ON "BLOODBANK"."LOGIN_DETAIL" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATION_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."LOCATION_INFO_PK" ON "BLOODBANK"."LOCATION_INFO" ("LOC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INQUIRY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."INQUIRY_PK" ON "BLOODBANK"."INQUIRY" ("INQ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_ASSIGNMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."EMPLOYEE_ASSIGNMENT_PK" ON "BLOODBANK"."EMPREQ_ASSIGNMENT" ("EA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPDON_ASSIGNMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."EMPDON_ASSIGNMENT_PK" ON "BLOODBANK"."EMPDON_ASSIGNMENT" ("EDA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008601
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."SYS_C008601" ON "BLOODBANK"."EMP" ("EMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DONATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."DONATION_PK" ON "BLOODBANK"."DONATION" ("D_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008599
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."SYS_C008599" ON "BLOODBANK"."DEPT" ("DEPTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEMO_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."DEMO_USERS_PK" ON "BLOODBANK"."DEMO_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEMO_PRODUCT_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."DEMO_PRODUCT_INFO_PK" ON "BLOODBANK"."DEMO_PRODUCT_INFO" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEMO_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."DEMO_ORDER_PK" ON "BLOODBANK"."DEMO_ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEMO_ORD_CUSTOMER_IX
--------------------------------------------------------

  CREATE INDEX "BLOODBANK"."DEMO_ORD_CUSTOMER_IX" ON "BLOODBANK"."DEMO_ORDERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEMO_ORDER_ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."DEMO_ORDER_ITEMS_PK" ON "BLOODBANK"."DEMO_ORDER_ITEMS" ("ORDER_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEMO_CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOODBANK"."DEMO_CUSTOMERS_PK" ON "BLOODBANK"."DEMO_CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEMO_CUST_NAME_IX
--------------------------------------------------------

  CREATE INDEX "BLOODBANK"."DEMO_CUST_NAME_IX" ON "BLOODBANK"."DEMO_CUSTOMERS" ("CUST_LAST_NAME", "CUST_FIRST_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger BI_DEMO_USERS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BLOODBANK"."BI_DEMO_USERS" 
BEFORE
insert on "DEMO_USERS"
for each row
begin
begin
  for c1 in (
    select DEMO_USERS_SEQ.nextval next_val
    from dual
  ) loop
    :new.USER_ID :=  c1.next_val;
    :new.admin_user := 'N';
    :new.created_on := sysdate;
  end loop;
end;
end;
/
ALTER TRIGGER "BLOODBANK"."BI_DEMO_USERS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEMO_USERS_T1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BLOODBANK"."DEMO_USERS_T1" 
BEFORE
insert or update on "DEMO_USERS"
for each row
begin
:NEW.user_name := upper(:NEW.user_name);
end;
/
ALTER TRIGGER "BLOODBANK"."DEMO_USERS_T1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERT_DEMO_PROD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BLOODBANK"."INSERT_DEMO_PROD" 
BEFORE INSERT ON demo_product_info
FOR EACH ROW
DECLARE
  prod_id number;
BEGIN
  SELECT demo_prod_seq.nextval
    INTO prod_id
    FROM dual;
  :new.PRODUCT_ID := prod_id;
END;
/
ALTER TRIGGER "BLOODBANK"."INSERT_DEMO_PROD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERT_DEMO_ORDER_ITEMS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BLOODBANK"."INSERT_DEMO_ORDER_ITEMS" 
BEFORE
insert on "DEMO_ORDER_ITEMS"
for each row
begin
declare
  order_item_id number;
begin
select demo_order_items_seq.nextval into order_item_id from dual;
:new.ORDER_ITEM_ID := order_item_id;
end;
end;
/
ALTER TRIGGER "BLOODBANK"."INSERT_DEMO_ORDER_ITEMS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPDATE_ORDER_TOTAL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BLOODBANK"."UPDATE_ORDER_TOTAL" 
after insert or update or delete on demo_order_items
begin

-- Update the Order Total when any order item is changed

update demo_orders set order_total =
  (select sum(unit_price*quantity) from demo_order_items
    where demo_order_items.order_id = demo_orders.order_id);
end;
/
ALTER TRIGGER "BLOODBANK"."UPDATE_ORDER_TOTAL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEMO_ORDER_ITEMS_GET_PRICE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BLOODBANK"."DEMO_ORDER_ITEMS_GET_PRICE" 
before insert or update on demo_order_items for each row
declare
  l_list_price number;
begin
-- First, we need to get the current list price of the order line item
select list_price into l_list_price from demo_product_info
  where product_id = :new.product_id;

-- Once we have the correct price, we will update the order line with the correct price
:new.unit_price := l_list_price;

end;
/
ALTER TRIGGER "BLOODBANK"."DEMO_ORDER_ITEMS_GET_PRICE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERT_DEMO_CUST
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BLOODBANK"."INSERT_DEMO_CUST" 
BEFORE INSERT ON demo_customers
FOR EACH ROW
DECLARE
  cust_id number;
BEGIN
  SELECT demo_cust_seq.nextval
    INTO cust_id
    FROM dual;
  :new.CUSTOMER_ID := cust_id;
END;
/
ALTER TRIGGER "BLOODBANK"."INSERT_DEMO_CUST" ENABLE;
--------------------------------------------------------
--  Constraints for Table BB_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."BB_EMPLOYEE" ADD CONSTRAINT "BB_EMPLOYEE_PK" PRIMARY KEY ("BBE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."BB_EMPLOYEE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BB_EMPLOYEE" MODIFY ("BB_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BB_EMPLOYEE" MODIFY ("BBE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOOD_BANK
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" ADD CONSTRAINT "BLOOD_BANK_PK" PRIMARY KEY ("BB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("LOC_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("CITY_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("STATE_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("BB_NAME" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_BANK" MODIFY ("BB_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOOD_REQUEST
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" ADD CONSTRAINT "BLOOD_REQUEST_PK" PRIMARY KEY ("BR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" MODIFY ("REQ_DATE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" MODIFY ("REQ_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" MODIFY ("BLD_GROUP" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" MODIFY ("BB_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" MODIFY ("BR_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."BLOOD_REQUEST" MODIFY ("ASSIGNTO_EMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITY_INFO
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."CITY_INFO" ADD CONSTRAINT "CITY_INFO_PK" PRIMARY KEY ("CITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."CITY_INFO" MODIFY ("STATE_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."CITY_INFO" MODIFY ("CITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."CITY_INFO" MODIFY ("CITY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATE_INFO
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."STATE_INFO" ADD CONSTRAINT "STATE_INFO_PK" PRIMARY KEY ("STATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."STATE_INFO" MODIFY ("STATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."STATE_INFO" MODIFY ("STATE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTRATION
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."REGISTRATION" ADD CONSTRAINT "REGISTRATION_PK" PRIMARY KEY ("REG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("PINCODE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("BIRTH_DATE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."REGISTRATION" MODIFY ("REG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGIN_DETAIL
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."LOGIN_DETAIL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."LOGIN_DETAIL" ADD CONSTRAINT "LOGIN_DETAIL_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."LOGIN_DETAIL" MODIFY ("USER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."LOGIN_DETAIL" MODIFY ("PROFILE_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."LOGIN_DETAIL" MODIFY ("ANSWER" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."LOGIN_DETAIL" MODIFY ("SEC_QUESTION" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."LOGIN_DETAIL" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."LOGIN_DETAIL" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION_INFO
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."LOCATION_INFO" MODIFY ("PIN_CODE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."LOCATION_INFO" ADD CONSTRAINT "LOCATION_INFO_PK" PRIMARY KEY ("LOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."LOCATION_INFO" MODIFY ("CITY_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."LOCATION_INFO" MODIFY ("LOC_NAME" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."LOCATION_INFO" MODIFY ("LOC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INQUIRY
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."INQUIRY" ADD CONSTRAINT "INQUIRY_PK" PRIMARY KEY ("INQ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."INQUIRY" MODIFY ("INQ_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."INQUIRY" MODIFY ("INQ_DATE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."INQUIRY" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."INQUIRY" MODIFY ("INQUIRY" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."INQUIRY" MODIFY ("INQ_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."INQUIRY" MODIFY ("INQUIRED_BY" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."INQUIRY" MODIFY ("INQ_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FEEDBACK
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."FEEDBACK" MODIFY ("FEEDBACK" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."FEEDBACK" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."FEEDBACK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."FEEDBACK" MODIFY ("F_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPREQ_ASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."EMPREQ_ASSIGNMENT" MODIFY ("APP_DATE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."EMPREQ_ASSIGNMENT" ADD CONSTRAINT "EMPLOYEE_ASSIGNMENT_PK" PRIMARY KEY ("EA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."EMPREQ_ASSIGNMENT" MODIFY ("REQ_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."EMPREQ_ASSIGNMENT" MODIFY ("E_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."EMPREQ_ASSIGNMENT" MODIFY ("U_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."EMPREQ_ASSIGNMENT" MODIFY ("EA_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."EMPREQ_ASSIGNMENT" MODIFY ("REQ_STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPDON_ASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."EMPDON_ASSIGNMENT" ADD CONSTRAINT "EMPDON_ASSIGNMENT_PK" PRIMARY KEY ("EDA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."EMPDON_ASSIGNMENT" MODIFY ("DONREQ_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."EMPDON_ASSIGNMENT" MODIFY ("EMP_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."EMPDON_ASSIGNMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."EMPDON_ASSIGNMENT" MODIFY ("EDA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."EMP" ADD PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."EMP" MODIFY ("EMPNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DONATION
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."DONATION" MODIFY ("AVAILABLITY" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DONATION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DONATION" ADD CONSTRAINT "DONATION_PK" PRIMARY KEY ("D_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."DONATION" MODIFY ("PROCESSED_BY" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DONATION" MODIFY ("D_DATE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DONATION" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DONATION" MODIFY ("BGROUP" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DONATION" MODIFY ("BB_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DONATION" MODIFY ("REG_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DONATION" MODIFY ("D_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."DEPT" ADD PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEMO_USERS
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."DEMO_USERS" ADD CONSTRAINT "DEMO_USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEMO_PRODUCT_INFO
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."DEMO_PRODUCT_INFO" ADD CONSTRAINT "DEMO_PRODUCT_INFO_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."DEMO_PRODUCT_INFO" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMO_ORDERS
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."DEMO_ORDERS" ADD CONSTRAINT "DEMO_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."DEMO_ORDERS" ADD CONSTRAINT "DEMO_ORDER_TOTAL_MIN" CHECK (order_total >= 0) ENABLE;
  ALTER TABLE "BLOODBANK"."DEMO_ORDERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DEMO_ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMO_ORDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."DEMO_ORDER_ITEMS" ADD CONSTRAINT "DEMO_ORDER_ITEMS_PK" PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."DEMO_ORDER_ITEMS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DEMO_ORDER_ITEMS" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DEMO_ORDER_ITEMS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DEMO_ORDER_ITEMS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DEMO_ORDER_ITEMS" MODIFY ("ORDER_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMO_CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "BLOODBANK"."DEMO_CUSTOMERS" ADD CONSTRAINT "DEMO_CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BLOODBANK"."DEMO_CUSTOMERS" ADD CONSTRAINT "DEMO_CUST_CREDIT_LIMIT_MAX" CHECK (credit_limit <= 5000) ENABLE;
  ALTER TABLE "BLOODBANK"."DEMO_CUSTOMERS" MODIFY ("CUST_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DEMO_CUSTOMERS" MODIFY ("CUST_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "BLOODBANK"."DEMO_CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
